# Generated by Django 4.2.7 on 2023-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Python', max_length=15),
            preserve_default=False,
        ),
    ]
