# Generated by Django 4.2.7 on 2023-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default='1990-12-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='any', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default='any', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(default='any', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
