# Generated by Django 4.2.7 on 2023-11-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_added_at_user_city_user_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
