# Generated by Django 4.2.7 on 2023-11-19 20:05

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_user_added_at_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=main_app.models.generate_unique_name),
        ),
    ]
