# Generated by Django 4.2.7 on 2023-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.IntegerField(default=200),
        ),
    ]
