# Generated by Django 4.2.7 on 2023-11-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
