# Generated by Django 4.2.7 on 2023-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(to='main_app.product'),
        ),
    ]
