# Generated by Django 4.2.7 on 2023-11-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_orders_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
