# Generated by Django 4.2.7 on 2023-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-26'),
            preserve_default=False,
        ),
    ]
